import { serveSnapshotToBot, type AssetsBinding } from '../src/server/botPrerender';

// Known bots get the prerendered snapshot for the route; everyone else passes through
// to the existing app unchanged. Snapshots are generated by scripts/prerender.js.
export const onRequest = async (context: {
  request: Request;
  env: { ASSETS: AssetsBinding };
  next: () => Promise<Response>;
}): Promise<Response> => {
  const snapshot = await serveSnapshotToBot(context.request, context.env.ASSETS);
  return snapshot ?? context.next();
};
